## Exploratory Data Analysis

In [1]:
import pandas as pd
import numpy as np

# Supplier data
supplier_data = pd.read_csv("C:/Final-Year-Project-2025/data/raw/synthetic_supplier_dataset_1.csv")
supplier_data.info()
supplier_df = pd.DataFrame(supplier_data)
supplier_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5050 entries, 0 to 5049
Data columns (total 26 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Supplier_ID                         5050 non-null   object
 1   Supplier_Name                       5050 non-null   object
 2   Country                             5050 non-null   object
 3   Region                              5050 non-null   object
 4   Supplier_Tier                       5050 non-null   int64
 5   Industry_Sector                     5050 non-null   int64
 6   ESG_Score                           4942 non-null   float64
 7   Environmental_Score                 4958 non-null   float64
 8   Social_Score                        4953 non-null   float64
 9   Governance_Score                    4950 non-null   float64
 10  Carbon_Emission_Intensity           4963 non-null   float64
 11  Waste_Management_Efficiency         4943 non-null   float64
 12  Renewable_Energy_Usage              4949 non-null   float64
 13  Compliance_Level                    5050 non-null   int64
 14  Sustainability_Report_Availability  5050 non-null   int64
 15  Lead_Time_Days                      4990 non-null   float64
 16  Production_Capacity                 5007 non-null   float64
 17  On_Time_Delivery_Rate               4935 non-null   float64
 18  Defect_Rate                         4951 non-null   float64
 19  Financial_Stability_Score           4950 non-null   float64
 20  Cost_Index                          4962 non-null   float64
 21  Labour_Compliance_Score             4965 non-null   float64
 22  Diversity_Index                     4936 non-null   float64
 23  Supplier_Audit_Score                4933 non-null   float64
 24  Incident_History_Count              5002 non-null   float64
 25  Logistics_Distance_km               4992 non-null   float64
dtypes: float64(18), int64(4), object(4)
memory usage: 1.0+ MB

,Supplier_ID,Supplier_Name,Country,Region,Supplier_Tier,Industry_Sector,ESG_Score,Environmental_Score,Social_Score,Governance_Score,...,Production_Capacity,On_Time_Delivery_Rate,Defect_Rate,Financial_Stability_Score,Cost_Index,Labour_Compliance_Score,Diversity_Index,Supplier_Audit_Score,Incident_History_Count,Logistics_Distance_km
0,SUP0001,Dell Technologies,Italy,Europe,2,221112,61.60,100.00,NaN,91.79,...,9156.0,0.82,0.05,68.59,0.14,71.83,0.50,78.29,0.0,2289.0
1,SUP0002,Mitsubishi Heavy Industries,Canada,North America,2,331110,54.96,63.93,64.18,97.81,...,9311.0,1.00,0.06,60.89,0.55,70.41,0.08,75.95,0.0,6311.0
2,SUP0003,Lenovo Group,India,Asia-Pacific,3,423830,72.24,64.65,24.99,80.95,...,24168.0,0.86,0.04,65.25,0.34,84.58,0.68,68.05,2.0,1595.0
3,SUP0004,ExxonMobil,China,Asia-Pacific,1,336411,65.23,68.47,88.43,81.03,...,5712.0,0.86,0.08,58.70,0.72,77.72,0.50,92.17,1.0,4752.0
4,SUP0005,Dell Technologies,France,Europe,2,423830,87.32,81.77,NaN,84.74,...,11139.0,0.82,0.04,66.00,0.75,76.29,0.45,80.14,2.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5045,SUP3907,Foxconn Technology Group,United Kingdom,Europe,1,324110,74.80,74.94,73.47,57.16,...,4227.0,0.88,0.07,92.77,0.60,98.07,0.49,157.45,5.0,50.0
5046,SUP3774,Bosch GmbH,Australia,Asia-Pacific,2,331110,115.77,92.09,60.82,73.16,...,14263.0,0.95,0.06,100.00,0.67,87.46,0.65,63.62,5.0,4499.0
5047,SUP4636,IBM,Canada,North America,3,221112,53.18,176.35,83.92,86.71,...,20712.0,0.89,0.06,69.55,0.68,78.78,0.89,82.31,4.0,6541.0
5048,SUP3162,Tata Steel,France,Europe,3,325211,72.44,89.91,58.73,82.81,...,8797.0,0.75,0.08,77.50,0.74,86.96,0.68,89.72,0.0,2310.0
5049,SUP2660,Panasonic,Brazil,South America,2,423830,44.88,62.60,70.63,55.71,...,15872.0,0.92,0.05,84.99,0.24,78.12,0.58,80.40,6.0,2611.0

In [3]:
# CO2 emissions data
co2_data = pd.read_csv("C:/Final-Year-Project-2025/data/raw/owid-co2-data.csv")
co2_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50191 entries, 0 to 50190
Data columns (total 79 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   country                                    50191 non-null  object
 1   year                                       50191 non-null  int64
 2   iso_code                                   42262 non-null  object
 3   population                                 41019 non-null  float64
 4   gdp                                        15251 non-null  float64
 5   cement_co2                                 28863 non-null  float64
 6   cement_co2_per_capita                      25358 non-null  float64
 7   co2                                        29137 non-null  float64
 8   co2_growth_abs                             26981 non-null  float64
 9   co2_growth_prct                            26002 non-null  float64
 10  co2_including_luc                          23585 non-null  float64
 11  co2_including_luc_growth_abs               23285 non-null  float64
 12  co2_including_luc_growth_prct              23285 non-null  float64
 13  co2_including_luc_per_capita               23495 non-null  float64
 14  co2_including_luc_per_gdp                  16790 non-null  float64
 15  co2_including_luc_per_unit_energy          9701 non-null   float64
 16  co2_per_capita                             26182 non-null  float64
 17  co2_per_gdp                                17528 non-null  float64
 18  co2_per_unit_energy                        10350 non-null  float64
 19  coal_co2                                   21755 non-null  float64
 20  coal_co2_per_capita                        21050 non-null  float64
 21  consumption_co2                            4866 non-null   float64
 22  consumption_co2_per_capita                 4502 non-null   float64
 23  consumption_co2_per_gdp                    4444 non-null   float64
 24  cumulative_cement_co2                      28841 non-null  float64
 25  cumulative_co2                             27328 non-null  float64
 26  cumulative_co2_including_luc               23585 non-null  float64
 27  cumulative_coal_co2                        21755 non-null  float64
 28  cumulative_flaring_co2                     15891 non-null  float64
 29  cumulative_gas_co2                         18014 non-null  float64
 30  cumulative_luc_co2                         37236 non-null  float64
 31  cumulative_oil_co2                         25217 non-null  float64
 32  cumulative_other_co2                       3202 non-null   float64
 33  energy_per_capita                          10109 non-null  float64
 34  energy_per_gdp                             7696 non-null   float64
 35  flaring_co2                                15952 non-null  float64
 36  flaring_co2_per_capita                     14694 non-null  float64
 37  gas_co2                                    18014 non-null  float64
 38  gas_co2_per_capita                         17292 non-null  float64
 39  ghg_excluding_lucf_per_capita              35639 non-null  float64
 40  ghg_per_capita                             35813 non-null  float64
 41  land_use_change_co2                        37236 non-null  float64
 42  land_use_change_co2_per_capita             36434 non-null  float64
 43  methane                                    37410 non-null  float64
 44  methane_per_capita                         35813 non-null  float64
 45  nitrous_oxide                              38280 non-null  float64
 46  nitrous_oxide_per_capita                   36320 non-null  float64
 47  oil_co2                                    25218 non-null  float64
 48  oil_co2_per_capita                         24436 non-null  float64
 49  other_co2_per_capita                       2474 non-null   float64
 50  other_industry_co2                         3202 non-null   float64
 51  primary_energy_consumption                 10151 non-null  float64
 52  share_global_cement_co2                    21960 non-null  float64
 53  share_global_co2                           27328 non-null  float64
 54  share_global_co2_including_luc             23585 non-null  float64
 55  share_global_coal_co2                      21755 non-null  float64
 56  share_global_cumulative_cement_co2         21960 non-null  float64
 57  share_global_cumulative_co2                27328 non-null  float64
 58  share_global_cumulative_co2_including_luc  23585 non-null  float64
 59  share_global_cumulative_coal_co2           21755 non-null  float64
 60  share_global_cumulative_flaring_co2        10869 non-null  float64
 61  share_global_cumulative_gas_co2            15034 non-null  float64
 62  share_global_cumulative_luc_co2            37236 non-null  float64
 63  share_global_cumulative_oil_co2            23592 non-null  float64
 64  share_global_cumulative_other_co2          2108 non-null   float64
 65  share_global_flaring_co2                   10869 non-null  float64
 66  share_global_gas_co2                       15034 non-null  float64
 67  share_global_luc_co2                       37236 non-null  float64
 68  share_global_oil_co2                       23592 non-null  float64
 69  share_global_other_co2                     2108 non-null   float64
 70  share_of_temperature_change_from_ghg       41001 non-null  float64
 71  temperature_change_from_ch4                38060 non-null  float64
 72  temperature_change_from_co2                41001 non-null  float64
 73  temperature_change_from_ghg                41001 non-null  float64
 74  temperature_change_from_n2o                38060 non-null  float64
 75  total_ghg                                  37410 non-null  float64
 76  total_ghg_excluding_lucf                   37236 non-null  float64
 77  trade_co2                                  4535 non-null   float64
 78  trade_co2_share                            4535 non-null   float64
dtypes: float64(76), int64(1), object(2)
memory usage: 30.3+ MB

In [4]:
# GHG emissions data
ghg_data = pd.read_csv("C:/Final-Year-Project-2025/data/raw/SupplyChainGHGEmissionFactors_v1.2_NAICS_byGHG_USD2021.csv")
ghg_data.info()
ghg_df = pd.DataFrame(ghg_data)
ghg_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16256 entries, 0 to 16255
Data columns (total 8 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   2017 NAICS Code                                16256 non-null  int64
 1   2017 NAICS Title                               16256 non-null  object
 2   GHG                                            16256 non-null  object
 3   Unit                                           16256 non-null  object
 4   Supply Chain Emission Factors without Margins  16256 non-null  float64
 5   Margins of Supply Chain Emission Factors       16256 non-null  float64
 6   Supply Chain Emission Factors with Margins     16256 non-null  float64
 7   Reference USEEIO Code                          16256 non-null  object
dtypes: float64(3), int64(1), object(4)
memory usage: 1016.1+ KB

,2017 NAICS Code,2017 NAICS Title,GHG,Unit,Supply Chain Emission Factors without Margins,Margins of Supply Chain Emission Factors,Supply Chain Emission Factors with Margins,Reference USEEIO Code
0,111110,Soybean Farming,Carbon dioxide,"kg/2021 USD, purchaser price",4.040000e-01,9.110000e-02,4.950000e-01,1111A0
1,111110,Soybean Farming,Carbon tetrafluoride,"kg/2021 USD, purchaser price",1.940000e-08,2.870000e-09,2.230000e-08,1111A0
2,111110,Soybean Farming,Hexafluoroethane,"kg/2021 USD, purchaser price",4.210000e-09,5.900000e-10,4.800000e-09,1111A0
3,111110,Soybean Farming,"HFCs and PFCs, unspecified","kg/2021 USD, purchaser price",1.640000e-07,1.310000e-07,2.950000e-07,1111A0
4,111110,Soybean Farming,HFC-125,"kg/2021 USD, purchaser price",1.630000e-07,1.300000e-07,2.930000e-07,1111A0
...,...,...,...,...,...,...,...,...
16251,813990,"Other Similar Organizations (except Business, ...",Nitrous oxide,"kg/2021 USD, purchaser price",2.240000e-05,0.000000e+00,2.240000e-05,813B00
16252,813990,"Other Similar Organizations (except Business, ...",Hexafluoroethane,"kg/2021 USD, purchaser price",2.890000e-09,0.000000e+00,2.890000e-09,813B00
16253,813990,"Other Similar Organizations (except Business, ...",HFC-143a,"kg/2021 USD, purchaser price",4.690000e-07,0.000000e+00,4.690000e-07,813B00
16254,813990,"Other Similar Organizations (except Business, ...",HFC-23,"kg/2021 USD, purchaser price",4.560000e-09,0.000000e+00,4.560000e-09,813B00
16255,813990,"Other Similar Organizations (except Business, ...",Perfluorocyclobutane,"kg/2021 USD, purchaser price",1.260000e-10,0.000000e+00,1.260000e-10,813B00

In [5]:
# ESG data
# To be integrated with commodity and supplier data
esg_data = pd.read_csv("C:/Final-Year-Project-2025/data/raw/SP 500 ESG Risk Ratings.csv")
esg_data.info()
esg_df = pd.DataFrame(esg_data)
esg_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Symbol                  503 non-null    object
 1   Name                    503 non-null    object
 2   Address                 502 non-null    object
 3   Sector                  502 non-null    object
 4   Industry                502 non-null    object
 5   Full Time Employees     498 non-null    object
 6   Description             502 non-null    object
 7   Total ESG Risk score    430 non-null    float64
 8   Environment Risk Score  430 non-null    float64
 9   Governance Risk Score   430 non-null    float64
 10  Social Risk Score       430 non-null    float64
 11  Controversy Level       430 non-null    object
 12  Controversy Score       403 non-null    float64
 13  ESG Risk Percentile     430 non-null    object
 14  ESG Risk Level          430 non-null    object
dtypes: float64(5), object(10)
memory usage: 59.1+ KB

,Symbol,Name,Address,Sector,Industry,Full Time Employees,Description,Total ESG Risk score,Environment Risk Score,Governance Risk Score,Social Risk Score,Controversy Level,Controversy Score,ESG Risk Percentile,ESG Risk Level
0,ENPH,"Enphase Energy, Inc.","47281 Bayside Parkway\nFremont, CA 94538\nUnit...",Technology,Solar,"3,157","Enphase Energy, Inc., together with its subsid...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,EMN,Eastman Chemical Company,"200 South Wilcox Drive\nKingsport, TN 37662\nU...",Basic Materials,Specialty Chemicals,"14,000",Eastman Chemical Company operates as a special...,25.3,12.8,6.6,5.8,Moderate Controversy Level,2.0,50th percentile,Medium
2,DPZ,Domino's Pizza Inc.,"30 Frank Lloyd Wright Drive\nAnn Arbor, MI 481...",Consumer Cyclical,Restaurants,"6,500","Domino's Pizza, Inc., through its subsidiaries...",29.2,10.6,6.3,12.2,Moderate Controversy Level,2.0,66th percentile,Medium
3,DAY,"Dayforce, Inc.","3311 East Old Shakopee Road\nMinneapolis, MN 5...",Technology,Software - Application,"9,084","Dayforce Inc., together with its subsidiaries,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,DVA,Davita Inc.,"2000 16th Street\nDenver, CO 80202\nUnited States",Healthcare,Medical Care Facilities,"70,000",DaVita Inc. provides kidney dialysis services ...,22.6,0.1,8.4,14.1,Moderate Controversy Level,2.0,38th percentile,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,ACN,Accenture Plc,1 Grand Canal Square\nGrand Canal Harbour\nDub...,Technology,Information Technology Services,"742,000","Accenture plc, a professional services company...",9.8,0.8,4.4,4.6,Moderate Controversy Level,2.0,3rd percentile,Negligible
499,ABBV,Abbvie Inc.,"1 North Waukegan Road\nNorth Chicago, IL 60064...",Healthcare,Drug Manufacturers - General,"50,000","AbbVie Inc. discovers, develops, manufactures,...",29.9,2.4,10.4,17.2,Significant Controversy Level,3.0,69th percentile,Medium
500,ABT,Abbott Laboratories,100 Abbott Park Road\nAbbott Park\nNorth Chica...,Healthcare,Medical Devices,"114,000","Abbott Laboratories, together with its subsidi...",24.8,2.3,8.3,14.2,Significant Controversy Level,3.0,48th percentile,Medium
501,AOS,A.O. Smith Corporation,11270 West Park Place\nSuite 170 PO Box 245008...,Industrials,Specialty Industrial Machinery,"12,000",A. O. Smith Corporation manufactures and marke...,25.4,7.2,6.4,11.9,Low Controversy Level,1.0,51st percentile,Medium
502,MMM,3m Company,"3M Center\nSaint Paul, MN 55144-1000\nUnited S...",Industrials,Conglomerates,"85,000",3M Company provides diversified technology ser...,37.3,17.2,6.5,13.6,Severe Controversy Level,5.0,89th percentile,High